<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'toChina.club 表单 提交',
	'heading' => '新表单提交',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => '已选中',
		'checkbox_unchecked' => '未选中',
		'submitted_from' => '表单已从此网站提交：%s',
		'submitted_by' => '访客 IP 地址：%s',
		'too_many_submissions' => '此 IP 最近的提交太多',
		'failed_to_send_email' => '发送电子邮件失败',
		'invalid_reCAPTCHA_private_key' => 'reCAPTCHA 私钥无效。',
		'invalid_reCAPTCHA2_private_key' => 'reCAPTCHA 2.0 私钥无效。',
		'invalid_reCAPTCHA2_server_response' => 'reCAPTCHA 2.0 服务器响应无效。',
		'invalid_field_type' => '未知字段类型“%s”。',
		'invalid_form_config' => '字段“%s”有无效的配置。',
		'unknown_method' => '未知服务器请求方法'
	),
	'email' => array(
		'from' => 'iberachina@gmail.com',
		'to' => 'iberachina@gmail.com'
	),
	'fields' => array(
		'custom_U1581' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name：',
			'required' => true,
			'errors' => array(
				'required' => '字段“Name：”为必填字段。'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email：',
			'required' => true,
			'errors' => array(
				'required' => '字段“Email：”为必填字段。',
				'format' => '字段“Email：”有无效的电子邮箱。'
			)
		),
		'custom_U1575' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Massage：',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1626' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Phone Number：',
			'required' => true,
			'errors' => array(
				'required' => '字段“Phone Number：”为必填字段。'
			)
		)
	)
);

process_form($form);
?>
